[connections.snowflake]
account = "pja45566.east-us-2.azure"
user = "jytbrd"
password = "Snow2023flake"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "JAMF_DEVICE_INFO"
schema = "PUBLIC"
client_session_keep_alive = true